language: java
  before_install:
    - chmod +x mvnw
deploy:
  provider: heroku
    api-key: $HEROKU_API_KEY
      app: addressbookapplois
        on:
          all_branches: true
            skip_cleanup: true
            